import { rollup } from "npm:rollup";
import { minify } from "npm:terser";

let bundle = await rollup({
  input: "mod.js",
});

async function write_cdn_umd() {
  let { output } = await bundle.generate({
    format: "umd",
    name: "tinycolor",
  });
  let minified = await minify(output[0].code);
  const preamble = `// This file is autogenerated.
  // Ideally it wouldn't exist, but it's here for backwards compatibility for people
  // using it directly from a CDN. Please use the npm package which exports both CJS and ESM.
  // See https://github.com/bgrins/TinyColor/ for instructions.
  `;
  Deno.writeTextFileSync("tinycolor.js", preamble + output[0].code);
  Deno.writeTextFileSync("dist/tinycolor-min.js", preamble + minified.code);
}

async function write_npm_cjs() {
  let { output } = await bundle.generate({
    format: "umd",
    name: "tinycolor",
  });

  // Write necessary files for publishing commonjs to npm. The subdirectory
  // Sets { "type": "commonjs" } in the package.json, and includes a
  // lightweight test runner to run the same tests we do with ESM.
  Deno.writeTextFileSync(
    "./npm/cjs/tinycolor.js",
    `// This file is autogenerated. It's used to publish CJS to npm.
` + output[0].code
  );
  const test_template = Deno.readTextFileSync("./npm/cjs/test_template.js");
  const test_content = Deno.readTextFileSync("test.js");
  Deno.writeTextFileSync(
    "./npm/cjs/test.js",
    test_template.replace(
      "// CONTENT_GOES_HERE",
      test_content.substring(
        test_content.indexOf("// TEST_BEGINS_HERE"),
        test_content.length - 1
      )
    )
  );
}
async function write_npm_esm() {
  let { output } = await bundle.generate({
    format: "esm",
  });

  // Write necessary files for publishing commonjs to npm. The subdirectory
  // Sets { "type": "commonjs" } in the package.json, and includes a
  // lightweight test runner to run the same tests we do with ESM.
  Deno.writeTextFileSync(
    "./npm/esm/tinycolor.js",
    `// This file is autogenerated. It's used to publish ESM to npm.
` + output[0].code
  );
  const test_template = Deno.readTextFileSync("./npm/esm/test_template.js");
  const test_content = Deno.readTextFileSync("test.js");
  Deno.writeTextFileSync(
    "./npm/esm/test.js",
    test_template.replace(
      "// CONTENT_GOES_HERE",
      test_content.substring(
        test_content.indexOf("// TEST_BEGINS_HERE"),
        test_content.length - 1
      )
    )
  );
}

await write_cdn_umd();
await write_npm_cjs();
await write_npm_esm();